"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _blog_page from './blog-page.bones.json'

registerBones({
  "blog-page": _blog_page,
})
